### PR TITLE
[PATCH] Option to decide whether to prefix the other lang files or not is added.

### PR DESCRIPTION
**Pull request by pragatheeswarans**

### CODE REVIEW

**Comment by kamalaknn** [comment]
@pragatheeswarans can you explain what the `prefixOtherLangFiles` does?

**Comment by pragatheeswarans** [comment]
@kamalaknn As of now we prefix the prefixlabel to all files including other lang files. So some repos might have already used the lang files with the prefixlabel and the default file as a folder called "en". So in order to prevent prefixing those lang files, we get a config from them whether to prefix other lang files or only the default lang file.

**Comment by kamalaknn** [comment]
@pragatheeswarans There are two scenarios here.

1. The source files are stored as `en.properties`, `de.properties` etc. we transform them to `MessageResourcess_en.js`, `MessageResources_de.js` etc.

2. The source files are `en.properties` or `MessageResources_en.properties` and setting `outputFilePrefix: ''` will output as `en.js` or `MessageResources_en.js` without any prefix to the file names. 

So think about what you are trying to achieve here, `en.properties` and `MessageResource_de.properties` are now transformed to `MessageResources_en.js` and `MessageResources_de.js`. Isn't this asymmetric?

Moving `MessageResource_de.properties` to `de.properties` in the source should not break any existing flows, and makes more sense.

Think about it.

**Comment by pragatheeswarans** [comment]
@kamalaknn Yes. The source should contain en as a folder or property file and the other language files as de.properties, es.properties etc., 

But what if there are certain complications in renaming the files in the source? This is going to give a compatibility mode right?

**Comment by kamalaknn** [comment]
> But what if there are certain complications in renaming the files in the source?

What might be the case?

**Pull request closed without merging**
